---
title: "R Notebook"
output: html_notebook
---

```{r}
load('~/Downloads/data_brainspan_DFC.20190928.Rdata')
library(tidyr)
library(tidyverse)
library(dplyr)
library(ggplot2)
```

```{r}
# add a new column named "row_num" to the dataframe "e"
e<-e%>%
  mutate(row_num=1:52376)
```

```{r}
# convert the wide format dataframe "e" to a long format dataframe "e1"
e1 <- gather(e, column_num, expression_level, X1:X35, factor_key=TRUE)
```

```{r}
# remove all X from the dataframe "e1" in column "column_num"
e1<- e1%>%
  mutate(column_num=gsub("X","",e1$column_num))
```

```{r}
# merge two dataframes "e1" and "g" to a dataframe named "eg"
eg<-merge(e1, g, by="row_num")
```

```{r}
# merge two dataframes "eg" and "s" to a dataframe named "esg"
esg<-merge(eg, s, by="column_num")
```

```{r}
# change the name of columns in "esg" from " column_num" to "sample_num" and "row_num" to "gene_num"
colnames(esg)[1]<- ("sample_num")
colnames(esg)[2]<-("gene_num")
```

```{r}
# add two new columns "Developmental_period" and "Stage" according to sample's age
esg<- esg%>%
  mutate(Developmental_period=case_when(
    age%in%c("8 pcw", "9 pcw","12 pcw")~"early prenatal" ,
    age%in%c("13 pcw","16 pcw","17 pcw")~"early mid-prenatal",
    age%in%c("19 pcw","21 pcw","24 pcw")~"late mid-prenatal",
    age%in%c("26 pcw", "37 pcw")~"late prenatal",
    age == "4 mos" ~ "early infancy",
    age=="10 mos" ~ "late infancy",
    age %in% c("1 yrs","2 yrs","3 yrs","4 yrs") ~ "early childhood",
    age %in% c("8 yrs","11 yrs") ~ "late childhood",
    age %in% c("13 yrs","18 yrs","19 yrs") ~ "adolescence",
    TRUE ~ "adulthood"
  ))
esg<-esg%>%
  mutate(Stage=case_when(
    age%in%c("8 pcw", "9 pcw") ~ "2A",
    age=="12 pcw" ~ "2B",
    age=="13 pcw" ~ "3A",
    age%in%c("16 pcw","17 pcw") ~ "3B",
    age%in%c("19 pcw","21 pcw","24 pcw")~ "4",
    age%in%c("26 pcw", "37 pcw")~ "5",
    age == "4 mos" ~ "6",
    age=="10 mos" ~ "7",
    age %in% c("1 yrs","2 yrs","3 yrs","4 yrs") ~ "8",
    age %in% c("8 yrs","11 yrs") ~ "9",
    age %in% c("13 yrs","18 yrs","19 yrs") ~ "10",
    TRUE ~ "11"
  ))
```

```{r}
# convert dataframe "esg" to a tibble dataframe
esg<-as_tibble(esg)
```

```{r}
# mutate sample_num data to become numeric for reordering
esg<-esg%>%
  mutate(sample_num=as.numeric(sample_num))
```

```{r}
# filter rows with "TSPAN6" and which has expression level
TSPAN6<- esg%>%
  filter(gene_symbol=="TSPAN6"&expression_level>0.0)
```


```{r}
# comparing expression levels of "TSPAN6" gene from 8pcw to 40yrs in samples by sex
TSPAN6%>%
   mutate(Developmental_period = reorder(Developmental_period, sample_num)) %>%
  ggplot(aes(Developmental_period, expression_level, col=gender)) +
  geom_point() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```


```{r}
# comparing expression levels of "TSPAN6" gene from 8pcw to 40yrs in samples by sex
TSPAN6%>%
   mutate(Developmental_period = reorder(Developmental_period, sample_num)) %>%
  ggplot(aes(Developmental_period,expression_level, col=gender)) +
  geom_bar(stat="identity", fill="white")+
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```
```{r}
# comparing expression levels of "TSPAN6" gene from 8pcw to 40yrs in samples by sex
TSPAN6%>%
   mutate(Developmental_period = reorder(Developmental_period, sample_num)) %>%
  ggplot(aes(Developmental_period,expression_level, group=gender))+
  geom_line(position = "identity", aes(color=gender))+
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```


```{r}
# filter rows with several genes 
multiple<-esg%>%
  filter(gene_symbol%in%c("TSPAN6","KIF3B","CLIP2","KCTD2","ARPC1A")&expression_level>0.0)
```


```{r}
# comparing expression levels of several genes from 8pcw to 40yrs with developmental period
multiple%>%
  mutate(age=reorder(age, sample_num))%>%
  mutate(Developmental_period=reorder(Developmental_period, sample_num))%>%
  ggplot(aes(gene_symbol, expression_level))+
  geom_jitter(alpha = 0.8,aes(color=age))+
  facet_wrap(~Developmental_period, ncol=2)+
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

```{r}
# comparing expression levels of several genes from early prenatal to adulthood by sex
multiple%>%
   mutate(Developmental_period = reorder(Developmental_period, sample_num)) %>%
  ggplot(aes(Developmental_period,expression_level, group=gender))+
  geom_line(position = "identity",aes(color=gender))+
  theme(axis.text.x = element_text(angle = 45, hjust = 1))+
  facet_wrap(~gene_symbol, nrow=3)
```
