---
title: "R Notebook"
output: html_notebook
---

```{r}
library(ggplot2)
library(readxl)
library(dplyr)
library(tidyverse)
```


```{r}
d<-read_excel("~/Downloads/20200128_sanger.xlsx")
```

```{r}
d<-d%>%
  rename(PIK3CA_1634A=PIK3CA_E542...4)%>%
  rename(PIK3CA_1633G=PIK3CA_E542...5)%>%
  rename(PIK3CA_1658_1659GT=PIK3CA_E542...6)%>%
  gather("gene_name", "variation", 2:10)
```

```{r}
d1<-d%>%
  filter(variation!="-")
```

```{r}
d1<-d1%>%
  group_by(gene_name)%>%
  count()
d1<-as_tibble(d1)
```


```{r}
p1<-d1%>%
  ggplot(aes(gene_name,n, fill=gene_name))+
  geom_bar(stat = "identity", width=c(0.8))+
  theme(panel.background = element_rect("white"))+
  theme(axis.text.x = element_text(size = 10))+
  theme(axis.text.y = element_text(size = 10))+
  xlab("Variation types")+
  ylab("Counts")+
  theme(text = element_text(size = 12))+
  scale_fill_grey()+
  labs(fill = "Variation")+
  theme(legend.position="none")+
  geom_text(aes(label=n), vjust=0.5, color="black", size=3.5, nudge_y = 2)+
  scale_y_continuous(limits = c(0, 100))+
  coord_flip()
p1
```


```{r}
d2<-d%>%
  filter(variation!="-")
```


```{r}
d2<-d2%>%
  group_by(patient_number)%>%
  count(variation)
d2<-as_tibble(d2)
```


```{r}
d2<-d2%>%
  group_by(patient_number)%>%
  count()
d2<-as_tibble(d2)
```

```{r}
d2<-d2%>%
  group_by(n)%>%
  count()
d2<-as_tibble(d2)
```

```{r}
d2[1,1]="1 variation"
d2[2,1]="2 variations"
d2[3,1]="3 variations"
d2[4,1]="4 variations"
```


```{r}
p2<-d2%>%
  ggplot(aes(n,nn, color=n))+
  geom_bar(stat = "identity", fill="white",width=c(0.8))+
  theme_classic()+
  scale_color_grey()+
  geom_text(aes(label=nn), vjust=-0.4,col="black",size=4)+
  xlab("Variation number")+
  ylab("Counts")+
  theme(axis.text.x = element_text(size = 10))+
  theme(axis.text.y = element_text(size = 10))+
  theme(text = element_text(size = 12))+
  scale_y_continuous(limits = c(0, 60))+
  theme(legend.position="none")
p2
```


```{r}
p<-ggarrange(p1,p2, nrow = 2, labels = c("A", "B"))
p
```
```{r}
ggsave("SNU_final_assignment_plot_sanger_20200207.png", p)
```

